JWT_SECRET=1be188ed4924c179868da97b213748b5167be91e172409b734ef14999eb4c946
RABBIT_URI=amqps://zukvasvs:h7jRTWLlTHlVN45bUJYFS3izm5nkNynl@jaragua.lmq.cloudamqp.com/zukvasvs
DB_NAME=lalouisedb
DB_USERNAME=lalouise
DB_PASSWORD=lalouise123
MAIL_HOST=smtp.gmail.com
MAIL_USERNAME=seuemail@gmail.com
MAIL_PASSWORD=sua-app-password
