services:
  postgres:
    image: postgres:16
    container_name: lalouisedb
    environment:
      POSTGRES_DB: lalouisedb
      POSTGRES_USER: lalouise
      POSTGRES_PASSWORD: lalouise123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: